### ISSUE TITLE
./perform 10000 do nothing

### ISSUE THREAD

**Issue by apiot** [ramou/dfr#7]
Hello
I tried to run your code.
I clone it, then `make perform` then `./perform 10000` and nothing happens.

![Sélection_010](https://user-images.githubusercontent.com/7767164/68991832-81c24b00-0863-11ea-9557-1fe462c1132d.png)

Output of `lscpu`

```
Architecture :                          x86_64
Mode(s) opératoire(s) des processeurs : 32-bit, 64-bit
Boutisme :                              Little Endian
Processeur(s) :                         4
Liste de processeur(s) en ligne :       0-3
Thread(s) par cœur :                    1
Cœur(s) par socket :                    4
Socket(s) :                             1
Nœud(s) NUMA :                          1
Identifiant constructeur :              GenuineIntel
Famille de processeur :                 6
Modèle :                                60
Nom de modèle :                         Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Révision :                              3
Vitesse du processeur en MHz :          3780.758
Vitesse maximale du processeur en MHz : 3900,0000
Vitesse minimale du processeur en MHz : 800,0000
BogoMIPS :                              6983.91
Virtualisation :                        VT-x
Cache L1d :                             32K
Cache L1i :                             32K
Cache L2 :                              256K
Cache L3 :                              6144K
Nœud NUMA 0 de processeur(s) :          0-3
Drapaux :                               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d

```

**Comment by ramou** [comment]
The good news is the bug is pretty straightforward. I didn't run my own instructions. It wasn't until I looked at my makefile that I see that make is expecting `timing` not ``perform`.

I'll update the instructions (and put in the cd). If you could confirm that it is working once more, we're ok. Hey, I even see that I removed the debug flag which gives me the per-pass from this version...

**Comment by ramou** [comment]
...the bad news was that I feel like an idiot :P

**Comment by apiot** [comment]
Thx, it works now
(I don't have enough RAM for 10^9 integers) (RAM: 16GB)

![Sélection_013](https://user-images.githubusercontent.com/7767164/68995627-0dea6780-0890-11ea-851d-d285e8c48a16.png)

**Comment by ramou** [comment]
Oh wow, I want your processor for benchmarking! It's doing some of the nice optimizations that make my stuff look good! 

I'm gonna write a singularity image that lets you just run a command and it'll give proper benchamark data for mine, Ska Sort and RADULS so you don't have to work at it. Then I'm going to beg you to use it :D

**Comment by apiot** [comment]
No problem, I will run it.
You can write to me at: `name . surname @ lyart . fr`
Axelle Piot
